services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grader-app
    ports:
      - ${PORT}:3000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      - S3_ENDPOINT=minio-storage
      - S3_PORT=9001
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: unless-stopped
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
    container_name: minio-storage
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: server --address ":9001" --console-address ":9000" /data
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data:
